# Generated by Django 4.0.4 on 2022-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('age', models.ImageField(db_index=True, upload_to='', verbose_name='Год рождения')),
                ('salary', models.IntegerField(db_index=True, verbose_name='Зарплата')),
                ('skill', models.TextField(blank=True, db_index=True, verbose_name='Навыки')),
                ('image', models.ImageField(upload_to='image/%y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликованно')),
            ],
        ),
    ]
